server:
  port: ${PORT:40400}
  servlet:
    context-path: /auth
spring:
  application:
    name: gaoxi-auth
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.8.24:3306/dt55?characterEncoding=utf-8}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 10000
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
auth:
  tokenValiditySeconds: 1200
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: 127.0.0.1
  cookieMaxAge: -1
  urlBase: http://localhost:40400
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng

