spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.24:3306/dt55
    username: root
    password: root
    redis:
      host: ${REDIS_HOST:192.168.8.24}
      port: ${REDIS_PORT:6379}
      timeout: 5000 #连接超时 毫秒
      jedis:
        pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 1
          maxWait: -1 #连接池最大等行时间 -1没有限制
